name: output information

on: workflow_dispatch

jobs:
    info:
        runs-on: ubuntu-latest
        steps:
          - name: Get code
            uses: actions/checkout@v5
          - name: Display workflow information
            run: |
              echo "Workflow Information:"
              echo "------------------------"
              echo "${{ toJson(github) }}"
              echo "Workflow Name: ${{ github.workflow }}"
              echo "Event Name: ${{ github.event_name }}"
              echo "Repository: ${{ github.repository }}"
              echo "Ref: ${{ github.ref }}"
              echo "Actor: ${{ github.actor }}"
              echo "Run ID: ${{ github.run_id }}"
              echo "Run Number: ${{ github.run_number }}"
              echo "Job ID: ${{ github.job }}"
              echo "Run Attempt: ${{ github.run_attempt }}"
              echo "Workflow SHA: ${{ github.sha }}"
              echo "Workflow URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              

